/* 
 * XML Builder API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0.Final
 * Contact: projectopenubl+subscribe@googlegroups.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing DebitNoteOutputModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DebitNoteOutputModelTests
    {
        // TODO uncomment below to declare an instance variable for DebitNoteOutputModel
        //private DebitNoteOutputModel instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DebitNoteOutputModel
            //instance = new DebitNoteOutputModel();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DebitNoteOutputModel
        /// </summary>
        [Test]
        public void DebitNoteOutputModelInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DebitNoteOutputModel
            //Assert.IsInstanceOfType<DebitNoteOutputModel> (instance, "variable 'instance' is a DebitNoteOutputModel");
        }


        /// <summary>
        /// Test the property 'Cliente'
        /// </summary>
        [Test]
        public void ClienteTest()
        {
            // TODO unit test for the property 'Cliente'
        }
        /// <summary>
        /// Test the property 'Detalle'
        /// </summary>
        [Test]
        public void DetalleTest()
        {
            // TODO unit test for the property 'Detalle'
        }
        /// <summary>
        /// Test the property 'FechaEmision'
        /// </summary>
        [Test]
        public void FechaEmisionTest()
        {
            // TODO unit test for the property 'FechaEmision'
        }
        /// <summary>
        /// Test the property 'Firmante'
        /// </summary>
        [Test]
        public void FirmanteTest()
        {
            // TODO unit test for the property 'Firmante'
        }
        /// <summary>
        /// Test the property 'HoraEmision'
        /// </summary>
        [Test]
        public void HoraEmisionTest()
        {
            // TODO unit test for the property 'HoraEmision'
        }
        /// <summary>
        /// Test the property 'Impuestos'
        /// </summary>
        [Test]
        public void ImpuestosTest()
        {
            // TODO unit test for the property 'Impuestos'
        }
        /// <summary>
        /// Test the property 'Moneda'
        /// </summary>
        [Test]
        public void MonedaTest()
        {
            // TODO unit test for the property 'Moneda'
        }
        /// <summary>
        /// Test the property 'Proveedor'
        /// </summary>
        [Test]
        public void ProveedorTest()
        {
            // TODO unit test for the property 'Proveedor'
        }
        /// <summary>
        /// Test the property 'SerieNumero'
        /// </summary>
        [Test]
        public void SerieNumeroTest()
        {
            // TODO unit test for the property 'SerieNumero'
        }
        /// <summary>
        /// Test the property 'Totales'
        /// </summary>
        [Test]
        public void TotalesTest()
        {
            // TODO unit test for the property 'Totales'
        }
        /// <summary>
        /// Test the property 'DescripcionSustentoDeNota'
        /// </summary>
        [Test]
        public void DescripcionSustentoDeNotaTest()
        {
            // TODO unit test for the property 'DescripcionSustentoDeNota'
        }
        /// <summary>
        /// Test the property 'SerieNumeroComprobanteAfectado'
        /// </summary>
        [Test]
        public void SerieNumeroComprobanteAfectadoTest()
        {
            // TODO unit test for the property 'SerieNumeroComprobanteAfectado'
        }
        /// <summary>
        /// Test the property 'TipoDocumentoComprobanteAfectado'
        /// </summary>
        [Test]
        public void TipoDocumentoComprobanteAfectadoTest()
        {
            // TODO unit test for the property 'TipoDocumentoComprobanteAfectado'
        }
        /// <summary>
        /// Test the property 'TipoNota'
        /// </summary>
        [Test]
        public void TipoNotaTest()
        {
            // TODO unit test for the property 'TipoNota'
        }

    }

}
