/* 
 * XML Builder API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0.Final
 * Contact: projectopenubl+subscribe@googlegroups.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing SummaryDocumentComprobanteOutputModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SummaryDocumentComprobanteOutputModelTests
    {
        // TODO uncomment below to declare an instance variable for SummaryDocumentComprobanteOutputModel
        //private SummaryDocumentComprobanteOutputModel instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SummaryDocumentComprobanteOutputModel
            //instance = new SummaryDocumentComprobanteOutputModel();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SummaryDocumentComprobanteOutputModel
        /// </summary>
        [Test]
        public void SummaryDocumentComprobanteOutputModelInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SummaryDocumentComprobanteOutputModel
            //Assert.IsInstanceOfType<SummaryDocumentComprobanteOutputModel> (instance, "variable 'instance' is a SummaryDocumentComprobanteOutputModel");
        }


        /// <summary>
        /// Test the property 'Cliente'
        /// </summary>
        [Test]
        public void ClienteTest()
        {
            // TODO unit test for the property 'Cliente'
        }
        /// <summary>
        /// Test the property 'Impuestos'
        /// </summary>
        [Test]
        public void ImpuestosTest()
        {
            // TODO unit test for the property 'Impuestos'
        }
        /// <summary>
        /// Test the property 'SerieNumero'
        /// </summary>
        [Test]
        public void SerieNumeroTest()
        {
            // TODO unit test for the property 'SerieNumero'
        }
        /// <summary>
        /// Test the property 'Tipo'
        /// </summary>
        [Test]
        public void TipoTest()
        {
            // TODO unit test for the property 'Tipo'
        }
        /// <summary>
        /// Test the property 'ValorVenta'
        /// </summary>
        [Test]
        public void ValorVentaTest()
        {
            // TODO unit test for the property 'ValorVenta'
        }

    }

}
