/* 
 * XML Builder API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0.Final
 * Contact: projectopenubl+subscribe@googlegroups.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing SummaryDocumentOutputModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SummaryDocumentOutputModelTests
    {
        // TODO uncomment below to declare an instance variable for SummaryDocumentOutputModel
        //private SummaryDocumentOutputModel instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SummaryDocumentOutputModel
            //instance = new SummaryDocumentOutputModel();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SummaryDocumentOutputModel
        /// </summary>
        [Test]
        public void SummaryDocumentOutputModelInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SummaryDocumentOutputModel
            //Assert.IsInstanceOfType<SummaryDocumentOutputModel> (instance, "variable 'instance' is a SummaryDocumentOutputModel");
        }


        /// <summary>
        /// Test the property 'Detalle'
        /// </summary>
        [Test]
        public void DetalleTest()
        {
            // TODO unit test for the property 'Detalle'
        }
        /// <summary>
        /// Test the property 'FechaEmision'
        /// </summary>
        [Test]
        public void FechaEmisionTest()
        {
            // TODO unit test for the property 'FechaEmision'
        }
        /// <summary>
        /// Test the property 'FechaEmisionDeComprobantesAsociados'
        /// </summary>
        [Test]
        public void FechaEmisionDeComprobantesAsociadosTest()
        {
            // TODO unit test for the property 'FechaEmisionDeComprobantesAsociados'
        }
        /// <summary>
        /// Test the property 'Firmante'
        /// </summary>
        [Test]
        public void FirmanteTest()
        {
            // TODO unit test for the property 'Firmante'
        }
        /// <summary>
        /// Test the property 'Moneda'
        /// </summary>
        [Test]
        public void MonedaTest()
        {
            // TODO unit test for the property 'Moneda'
        }
        /// <summary>
        /// Test the property 'Proveedor'
        /// </summary>
        [Test]
        public void ProveedorTest()
        {
            // TODO unit test for the property 'Proveedor'
        }
        /// <summary>
        /// Test the property 'SerieNumero'
        /// </summary>
        [Test]
        public void SerieNumeroTest()
        {
            // TODO unit test for the property 'SerieNumero'
        }

    }

}
