# coding: utf-8

"""
    XML Builder API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0.Final
    Contact: projectopenubl+subscribe@googlegroups.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.impuesto_total_icb_output_model import ImpuestoTotalICBOutputModel  # noqa: E501
from swagger_client.rest import ApiException


class TestImpuestoTotalICBOutputModel(unittest.TestCase):
    """ImpuestoTotalICBOutputModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testImpuestoTotalICBOutputModel(self):
        """Test ImpuestoTotalICBOutputModel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.impuesto_total_icb_output_model.ImpuestoTotalICBOutputModel()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
