<?php
/**
 * DireccionOutputModelTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * XML Builder API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0.Final
 * Contact: projectopenubl+subscribe@googlegroups.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.18
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * DireccionOutputModelTest Class Doc Comment
 *
 * @category    Class
 * @description DireccionOutputModel
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class DireccionOutputModelTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "DireccionOutputModel"
     */
    public function testDireccionOutputModel()
    {
    }

    /**
     * Test attribute "codigo_local"
     */
    public function testPropertyCodigoLocal()
    {
    }

    /**
     * Test attribute "codigo_pais"
     */
    public function testPropertyCodigoPais()
    {
    }

    /**
     * Test attribute "departamento"
     */
    public function testPropertyDepartamento()
    {
    }

    /**
     * Test attribute "direccion"
     */
    public function testPropertyDireccion()
    {
    }

    /**
     * Test attribute "distrito"
     */
    public function testPropertyDistrito()
    {
    }

    /**
     * Test attribute "provincia"
     */
    public function testPropertyProvincia()
    {
    }

    /**
     * Test attribute "ubigeo"
     */
    public function testPropertyUbigeo()
    {
    }

    /**
     * Test attribute "urbanizacion"
     */
    public function testPropertyUrbanizacion()
    {
    }
}
