<?php
/**
 * InvoiceOutputModelTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * XML Builder API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0.Final
 * Contact: projectopenubl+subscribe@googlegroups.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.18
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * InvoiceOutputModelTest Class Doc Comment
 *
 * @category    Class
 * @description InvoiceOutputModel
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class InvoiceOutputModelTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "InvoiceOutputModel"
     */
    public function testInvoiceOutputModel()
    {
    }

    /**
     * Test attribute "cliente"
     */
    public function testPropertyCliente()
    {
    }

    /**
     * Test attribute "detalle"
     */
    public function testPropertyDetalle()
    {
    }

    /**
     * Test attribute "fecha_emision"
     */
    public function testPropertyFechaEmision()
    {
    }

    /**
     * Test attribute "firmante"
     */
    public function testPropertyFirmante()
    {
    }

    /**
     * Test attribute "hora_emision"
     */
    public function testPropertyHoraEmision()
    {
    }

    /**
     * Test attribute "impuestos"
     */
    public function testPropertyImpuestos()
    {
    }

    /**
     * Test attribute "moneda"
     */
    public function testPropertyMoneda()
    {
    }

    /**
     * Test attribute "proveedor"
     */
    public function testPropertyProveedor()
    {
    }

    /**
     * Test attribute "serie_numero"
     */
    public function testPropertySerieNumero()
    {
    }

    /**
     * Test attribute "totales"
     */
    public function testPropertyTotales()
    {
    }

    /**
     * Test attribute "tipo_invoice"
     */
    public function testPropertyTipoInvoice()
    {
    }
}
