<?php
/**
 * VoidedDocumentOutputModelTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * XML Builder API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0.Final
 * Contact: projectopenubl+subscribe@googlegroups.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.18
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * VoidedDocumentOutputModelTest Class Doc Comment
 *
 * @category    Class
 * @description VoidedDocumentOutputModel
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class VoidedDocumentOutputModelTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "VoidedDocumentOutputModel"
     */
    public function testVoidedDocumentOutputModel()
    {
    }

    /**
     * Test attribute "comprobante"
     */
    public function testPropertyComprobante()
    {
    }

    /**
     * Test attribute "descripcion_sustento"
     */
    public function testPropertyDescripcionSustento()
    {
    }

    /**
     * Test attribute "fecha_emision"
     */
    public function testPropertyFechaEmision()
    {
    }

    /**
     * Test attribute "firmante"
     */
    public function testPropertyFirmante()
    {
    }

    /**
     * Test attribute "proveedor"
     */
    public function testPropertyProveedor()
    {
    }

    /**
     * Test attribute "serie_numero"
     */
    public function testPropertySerieNumero()
    {
    }
}
