/* 
 * XML Builder API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0.Final
 * Contact: projectopenubl+subscribe@googlegroups.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Defines Catalog7_1
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
        public enum Catalog71
    {
        /// <summary>
        /// Enum EXONERADO for value: EXONERADO
        /// </summary>
        [EnumMember(Value = "EXONERADO")]
        EXONERADO = 1,
        /// <summary>
        /// Enum EXPORTACION for value: EXPORTACION
        /// </summary>
        [EnumMember(Value = "EXPORTACION")]
        EXPORTACION = 2,
        /// <summary>
        /// Enum GRATUITA for value: GRATUITA
        /// </summary>
        [EnumMember(Value = "GRATUITA")]
        GRATUITA = 3,
        /// <summary>
        /// Enum GRAVADO for value: GRAVADO
        /// </summary>
        [EnumMember(Value = "GRAVADO")]
        GRAVADO = 4,
        /// <summary>
        /// Enum INAFECTO for value: INAFECTO
        /// </summary>
        [EnumMember(Value = "INAFECTO")]
        INAFECTO = 5    }
}
