/* 
 * XML Builder API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0.Final
 * Contact: projectopenubl+subscribe@googlegroups.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Defines Catalog9
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
        public enum Catalog9
    {
        /// <summary>
        /// Enum ANULACIONDELAOPERACION for value: ANULACION_DE_LA_OPERACION
        /// </summary>
        [EnumMember(Value = "ANULACION_DE_LA_OPERACION")]
        ANULACIONDELAOPERACION = 1,
        /// <summary>
        /// Enum ANULACIONPORERRORENELRUC for value: ANULACION_POR_ERROR_EN_EL_RUC
        /// </summary>
        [EnumMember(Value = "ANULACION_POR_ERROR_EN_EL_RUC")]
        ANULACIONPORERRORENELRUC = 2,
        /// <summary>
        /// Enum BONIFICACION for value: BONIFICACION
        /// </summary>
        [EnumMember(Value = "BONIFICACION")]
        BONIFICACION = 3,
        /// <summary>
        /// Enum CORRECCIONPORERRORENLADESCRIPCION for value: CORRECCION_POR_ERROR_EN_LA_DESCRIPCION
        /// </summary>
        [EnumMember(Value = "CORRECCION_POR_ERROR_EN_LA_DESCRIPCION")]
        CORRECCIONPORERRORENLADESCRIPCION = 4,
        /// <summary>
        /// Enum DESCUENTOGLOBAL for value: DESCUENTO_GLOBAL
        /// </summary>
        [EnumMember(Value = "DESCUENTO_GLOBAL")]
        DESCUENTOGLOBAL = 5,
        /// <summary>
        /// Enum DESCUENTOPORITEM for value: DESCUENTO_POR_ITEM
        /// </summary>
        [EnumMember(Value = "DESCUENTO_POR_ITEM")]
        DESCUENTOPORITEM = 6,
        /// <summary>
        /// Enum DEVOLUCIONPORITEM for value: DEVOLUCION_POR_ITEM
        /// </summary>
        [EnumMember(Value = "DEVOLUCION_POR_ITEM")]
        DEVOLUCIONPORITEM = 7,
        /// <summary>
        /// Enum DEVOLUCIONTOTAL for value: DEVOLUCION_TOTAL
        /// </summary>
        [EnumMember(Value = "DEVOLUCION_TOTAL")]
        DEVOLUCIONTOTAL = 8,
        /// <summary>
        /// Enum DISMINUCIONENELVALOR for value: DISMINUCION_EN_EL_VALOR
        /// </summary>
        [EnumMember(Value = "DISMINUCION_EN_EL_VALOR")]
        DISMINUCIONENELVALOR = 9,
        /// <summary>
        /// Enum OTROSCONCEPTOS for value: OTROS_CONCEPTOS
        /// </summary>
        [EnumMember(Value = "OTROS_CONCEPTOS")]
        OTROSCONCEPTOS = 10    }
}
