/* 
 * XML Builder API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0.Final
 * Contact: projectopenubl+subscribe@googlegroups.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Defines Catalog6
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
        public enum Catalog6
    {
        /// <summary>
        /// Enum DECDIPLOMATICA for value: DEC_DIPLOMATICA
        /// </summary>
        [EnumMember(Value = "DEC_DIPLOMATICA")]
        DECDIPLOMATICA = 1,
        /// <summary>
        /// Enum DNI for value: DNI
        /// </summary>
        [EnumMember(Value = "DNI")]
        DNI = 2,
        /// <summary>
        /// Enum DOCTRIBNODOMSINRUC for value: DOC_TRIB_NO_DOM_SIN_RUC
        /// </summary>
        [EnumMember(Value = "DOC_TRIB_NO_DOM_SIN_RUC")]
        DOCTRIBNODOMSINRUC = 3,
        /// <summary>
        /// Enum EXTRANJERIA for value: EXTRANJERIA
        /// </summary>
        [EnumMember(Value = "EXTRANJERIA")]
        EXTRANJERIA = 4,
        /// <summary>
        /// Enum PASAPORTE for value: PASAPORTE
        /// </summary>
        [EnumMember(Value = "PASAPORTE")]
        PASAPORTE = 5,
        /// <summary>
        /// Enum RUC for value: RUC
        /// </summary>
        [EnumMember(Value = "RUC")]
        RUC = 6    }
}
