/* 
 * XML Builder API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0.Final
 * Contact: projectopenubl+subscribe@googlegroups.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Defines Catalog1
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
        public enum Catalog1
    {
        /// <summary>
        /// Enum BOLETA for value: BOLETA
        /// </summary>
        [EnumMember(Value = "BOLETA")]
        BOLETA = 1,
        /// <summary>
        /// Enum COMPROBANTEPAGOSEAE for value: COMPROBANTE_PAGO_SEAE
        /// </summary>
        [EnumMember(Value = "COMPROBANTE_PAGO_SEAE")]
        COMPROBANTEPAGOSEAE = 2,
        /// <summary>
        /// Enum DOCUMENTOSAFP for value: DOCUMENTOS_AFP
        /// </summary>
        [EnumMember(Value = "DOCUMENTOS_AFP")]
        DOCUMENTOSAFP = 3,
        /// <summary>
        /// Enum DOCUMENTOSFINANCIEROS for value: DOCUMENTOS_FINANCIEROS
        /// </summary>
        [EnumMember(Value = "DOCUMENTOS_FINANCIEROS")]
        DOCUMENTOSFINANCIEROS = 4,
        /// <summary>
        /// Enum FACTURA for value: FACTURA
        /// </summary>
        [EnumMember(Value = "FACTURA")]
        FACTURA = 5,
        /// <summary>
        /// Enum GUIAREMISIONREMITENTE for value: GUIA_REMISION_REMITENTE
        /// </summary>
        [EnumMember(Value = "GUIA_REMISION_REMITENTE")]
        GUIAREMISIONREMITENTE = 6,
        /// <summary>
        /// Enum GUIAREMISIONREMITENTECOMPLEMENTARIA for value: GUIA_REMISION_REMITENTE_COMPLEMENTARIA
        /// </summary>
        [EnumMember(Value = "GUIA_REMISION_REMITENTE_COMPLEMENTARIA")]
        GUIAREMISIONREMITENTECOMPLEMENTARIA = 7,
        /// <summary>
        /// Enum GUIAREMISIONTRANSPORTISTA for value: GUIA_REMISION_TRANSPORTISTA
        /// </summary>
        [EnumMember(Value = "GUIA_REMISION_TRANSPORTISTA")]
        GUIAREMISIONTRANSPORTISTA = 8,
        /// <summary>
        /// Enum GUIAREMISIONTRANSPORTISTACOMPLEMENTARIA for value: GUIA_REMISION_TRANSPORTISTA_COMPLEMENTARIA
        /// </summary>
        [EnumMember(Value = "GUIA_REMISION_TRANSPORTISTA_COMPLEMENTARIA")]
        GUIAREMISIONTRANSPORTISTACOMPLEMENTARIA = 9,
        /// <summary>
        /// Enum NOTACREDITO for value: NOTA_CREDITO
        /// </summary>
        [EnumMember(Value = "NOTA_CREDITO")]
        NOTACREDITO = 10,
        /// <summary>
        /// Enum NOTADEBITO for value: NOTA_DEBITO
        /// </summary>
        [EnumMember(Value = "NOTA_DEBITO")]
        NOTADEBITO = 11,
        /// <summary>
        /// Enum PERCEPCION for value: PERCEPCION
        /// </summary>
        [EnumMember(Value = "PERCEPCION")]
        PERCEPCION = 12,
        /// <summary>
        /// Enum PERCEPCIONVENTAINTERNA for value: PERCEPCION_VENTA_INTERNA
        /// </summary>
        [EnumMember(Value = "PERCEPCION_VENTA_INTERNA")]
        PERCEPCIONVENTAINTERNA = 13,
        /// <summary>
        /// Enum RETENCION for value: RETENCION
        /// </summary>
        [EnumMember(Value = "RETENCION")]
        RETENCION = 14,
        /// <summary>
        /// Enum TICKETMAQUINAREGISTRADORA for value: TICKET_MAQUINA_REGISTRADORA
        /// </summary>
        [EnumMember(Value = "TICKET_MAQUINA_REGISTRADORA")]
        TICKETMAQUINAREGISTRADORA = 15    }
}
