/* 
 * XML Builder API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0.Final
 * Contact: projectopenubl+subscribe@googlegroups.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// ImpuestoDetalladoIGVOutputModel
    /// </summary>
    [DataContract]
        public partial class ImpuestoDetalladoIGVOutputModel :  IEquatable<ImpuestoDetalladoIGVOutputModel>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ImpuestoDetalladoIGVOutputModel" /> class.
        /// </summary>
        /// <param name="categoria">categoria (required).</param>
        /// <param name="importe">importe (required).</param>
        /// <param name="baseImponible">baseImponible (required).</param>
        /// <param name="porcentaje">porcentaje (required).</param>
        /// <param name="tipo">tipo (required).</param>
        public ImpuestoDetalladoIGVOutputModel( categoria = default(),  importe = default(),  baseImponible = default(),  porcentaje = default(),  tipo = default())
        {
            // to ensure "categoria" is required (not null)
            if (categoria == null)
            {
                throw new InvalidDataException("categoria is a required property for ImpuestoDetalladoIGVOutputModel and cannot be null");
            }
            else
            {
                this.Categoria = categoria;
            }
            // to ensure "importe" is required (not null)
            if (importe == null)
            {
                throw new InvalidDataException("importe is a required property for ImpuestoDetalladoIGVOutputModel and cannot be null");
            }
            else
            {
                this.Importe = importe;
            }
            // to ensure "baseImponible" is required (not null)
            if (baseImponible == null)
            {
                throw new InvalidDataException("baseImponible is a required property for ImpuestoDetalladoIGVOutputModel and cannot be null");
            }
            else
            {
                this.BaseImponible = baseImponible;
            }
            // to ensure "porcentaje" is required (not null)
            if (porcentaje == null)
            {
                throw new InvalidDataException("porcentaje is a required property for ImpuestoDetalladoIGVOutputModel and cannot be null");
            }
            else
            {
                this.Porcentaje = porcentaje;
            }
            // to ensure "tipo" is required (not null)
            if (tipo == null)
            {
                throw new InvalidDataException("tipo is a required property for ImpuestoDetalladoIGVOutputModel and cannot be null");
            }
            else
            {
                this.Tipo = tipo;
            }
        }
        
        /// <summary>
        /// Gets or Sets Categoria
        /// </summary>
        [DataMember(Name="categoria", EmitDefaultValue=false)]
        public  Categoria { get; set; }

        /// <summary>
        /// Gets or Sets Importe
        /// </summary>
        [DataMember(Name="importe", EmitDefaultValue=false)]
        public  Importe { get; set; }

        /// <summary>
        /// Gets or Sets BaseImponible
        /// </summary>
        [DataMember(Name="baseImponible", EmitDefaultValue=false)]
        public  BaseImponible { get; set; }

        /// <summary>
        /// Gets or Sets Porcentaje
        /// </summary>
        [DataMember(Name="porcentaje", EmitDefaultValue=false)]
        public  Porcentaje { get; set; }

        /// <summary>
        /// Gets or Sets Tipo
        /// </summary>
        [DataMember(Name="tipo", EmitDefaultValue=false)]
        public  Tipo { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ImpuestoDetalladoIGVOutputModel {\n");
            sb.Append("  Categoria: ").Append(Categoria).Append("\n");
            sb.Append("  Importe: ").Append(Importe).Append("\n");
            sb.Append("  BaseImponible: ").Append(BaseImponible).Append("\n");
            sb.Append("  Porcentaje: ").Append(Porcentaje).Append("\n");
            sb.Append("  Tipo: ").Append(Tipo).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ImpuestoDetalladoIGVOutputModel);
        }

        /// <summary>
        /// Returns true if ImpuestoDetalladoIGVOutputModel instances are equal
        /// </summary>
        /// <param name="input">Instance of ImpuestoDetalladoIGVOutputModel to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ImpuestoDetalladoIGVOutputModel input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Categoria == input.Categoria ||
                    (this.Categoria != null &&
                    this.Categoria.Equals(input.Categoria))
                ) && 
                (
                    this.Importe == input.Importe ||
                    (this.Importe != null &&
                    this.Importe.Equals(input.Importe))
                ) && 
                (
                    this.BaseImponible == input.BaseImponible ||
                    (this.BaseImponible != null &&
                    this.BaseImponible.Equals(input.BaseImponible))
                ) && 
                (
                    this.Porcentaje == input.Porcentaje ||
                    (this.Porcentaje != null &&
                    this.Porcentaje.Equals(input.Porcentaje))
                ) && 
                (
                    this.Tipo == input.Tipo ||
                    (this.Tipo != null &&
                    this.Tipo.Equals(input.Tipo))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Categoria != null)
                    hashCode = hashCode * 59 + this.Categoria.GetHashCode();
                if (this.Importe != null)
                    hashCode = hashCode * 59 + this.Importe.GetHashCode();
                if (this.BaseImponible != null)
                    hashCode = hashCode * 59 + this.BaseImponible.GetHashCode();
                if (this.Porcentaje != null)
                    hashCode = hashCode * 59 + this.Porcentaje.GetHashCode();
                if (this.Tipo != null)
                    hashCode = hashCode * 59 + this.Tipo.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
