/* 
 * XML Builder API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0.Final
 * Contact: projectopenubl+subscribe@googlegroups.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// TotalValorVentaOutputModel
    /// </summary>
    [DataContract]
        public partial class TotalValorVentaOutputModel :  IEquatable<TotalValorVentaOutputModel>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TotalValorVentaOutputModel" /> class.
        /// </summary>
        /// <param name="importe">importe (required).</param>
        /// <param name="tipo">tipo (required).</param>
        public TotalValorVentaOutputModel( importe = default(),  tipo = default())
        {
            // to ensure "importe" is required (not null)
            if (importe == null)
            {
                throw new InvalidDataException("importe is a required property for TotalValorVentaOutputModel and cannot be null");
            }
            else
            {
                this.Importe = importe;
            }
            // to ensure "tipo" is required (not null)
            if (tipo == null)
            {
                throw new InvalidDataException("tipo is a required property for TotalValorVentaOutputModel and cannot be null");
            }
            else
            {
                this.Tipo = tipo;
            }
        }
        
        /// <summary>
        /// Gets or Sets Importe
        /// </summary>
        [DataMember(Name="importe", EmitDefaultValue=false)]
        public  Importe { get; set; }

        /// <summary>
        /// Gets or Sets Tipo
        /// </summary>
        [DataMember(Name="tipo", EmitDefaultValue=false)]
        public  Tipo { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class TotalValorVentaOutputModel {\n");
            sb.Append("  Importe: ").Append(Importe).Append("\n");
            sb.Append("  Tipo: ").Append(Tipo).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as TotalValorVentaOutputModel);
        }

        /// <summary>
        /// Returns true if TotalValorVentaOutputModel instances are equal
        /// </summary>
        /// <param name="input">Instance of TotalValorVentaOutputModel to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TotalValorVentaOutputModel input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Importe == input.Importe ||
                    (this.Importe != null &&
                    this.Importe.Equals(input.Importe))
                ) && 
                (
                    this.Tipo == input.Tipo ||
                    (this.Tipo != null &&
                    this.Tipo.Equals(input.Tipo))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Importe != null)
                    hashCode = hashCode * 59 + this.Importe.GetHashCode();
                if (this.Tipo != null)
                    hashCode = hashCode * 59 + this.Tipo.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
