<?php
/**
 * Catalog10
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * XML Builder API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0.Final
 * Contact: projectopenubl+subscribe@googlegroups.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.18
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;
use \Swagger\Client\ObjectSerializer;

/**
 * Catalog10 Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class Catalog10
{
    /**
     * Possible values of this enum
     */
    const AUMENTO_EN_EL_VALOR = 'AUMENTO_EN_EL_VALOR';
const INTERES_POR_MORA = 'INTERES_POR_MORA';
const PENALIDAD_OTROS_CONCEPTOS = 'PENALIDAD_OTROS_CONCEPTOS';
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::AUMENTO_EN_EL_VALOR,
self::INTERES_POR_MORA,
self::PENALIDAD_OTROS_CONCEPTOS,        ];
    }
}
