<?php
/**
 * Catalog16
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * XML Builder API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0.Final
 * Contact: projectopenubl+subscribe@googlegroups.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.18
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;
use \Swagger\Client\ObjectSerializer;

/**
 * Catalog16 Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class Catalog16
{
    /**
     * Possible values of this enum
     */
    const PRECIO_UNITARIO_INCLUYE_IGV = 'PRECIO_UNITARIO_INCLUYE_IGV';
const VALOR_FERENCIAL_UNITARIO_EN_OPERACIONES_NO_ONEROSAS = 'VALOR_FERENCIAL_UNITARIO_EN_OPERACIONES_NO_ONEROSAS';
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::PRECIO_UNITARIO_INCLUYE_IGV,
self::VALOR_FERENCIAL_UNITARIO_EN_OPERACIONES_NO_ONEROSAS,        ];
    }
}
