/*
 * XML Builder API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0.Final
 * Contact: projectopenubl+subscribe@googlegroups.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.CreditNote;
import io.swagger.client.model.DebitNote;
import io.swagger.client.model.Invoice;
import io.swagger.client.model.SummaryDocument;
import io.swagger.client.model.VoidedDocument;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CreateApi
 */
@Ignore
public class CreateApiTest {

    private final CreateApi api = new CreateApi();

    /**
     * Create a XML file from the input
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void apiDocumentsCreditNoteCreatePostTest() throws ApiException {
        CreditNote body = null;
        String response = api.apiDocumentsCreditNoteCreatePost(body);

        // TODO: test validations
    }
    /**
     * Create a XML file from the input
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void apiDocumentsDebitNoteCreatePostTest() throws ApiException {
        DebitNote body = null;
        String response = api.apiDocumentsDebitNoteCreatePost(body);

        // TODO: test validations
    }
    /**
     * Create a XML file from the input
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void apiDocumentsInvoiceCreatePostTest() throws ApiException {
        Invoice body = null;
        String response = api.apiDocumentsInvoiceCreatePost(body);

        // TODO: test validations
    }
    /**
     * Create a XML file from the input
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void apiDocumentsSummaryDocumentCreatePostTest() throws ApiException {
        SummaryDocument body = null;
        String response = api.apiDocumentsSummaryDocumentCreatePost(body);

        // TODO: test validations
    }
    /**
     * Create a XML file from the input
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void apiDocumentsVoidedDocumentCreatePostTest() throws ApiException {
        VoidedDocument body = null;
        String response = api.apiDocumentsVoidedDocumentCreatePost(body);

        // TODO: test validations
    }
}
