/*
 * XML Builder API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0.Final
 * Contact: projectopenubl+subscribe@googlegroups.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.annotations.SerializedName;
import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets Catalog16
 */
@JsonAdapter(Catalog16.Adapter.class)
public enum Catalog16 {
  PRECIO_UNITARIO_INCLUYE_IGV("PRECIO_UNITARIO_INCLUYE_IGV"),
  VALOR_FERENCIAL_UNITARIO_EN_OPERACIONES_NO_ONEROSAS("VALOR_FERENCIAL_UNITARIO_EN_OPERACIONES_NO_ONEROSAS");

  private String value;

  Catalog16(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static Catalog16 fromValue(String text) {
    for (Catalog16 b : Catalog16.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<Catalog16> {
    @Override
    public void write(final JsonWriter jsonWriter, final Catalog16 enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public Catalog16 read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return Catalog16.fromValue(String.valueOf(value));
    }
  }
}
