/*
 * XML Builder API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0.Final
 * Contact: projectopenubl+subscribe@googlegroups.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.ContactoOutputModel;
import io.swagger.client.model.DireccionOutputModel;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * ClienteOutputModel
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-04-03T17:52:28.678Z[GMT]")
public class ClienteOutputModel {
  @SerializedName("contacto")
  private ContactoOutputModel contacto = null;

  @SerializedName("direccion")
  private DireccionOutputModel direccion = null;

  @SerializedName("nombre")
  private String nombre = null;

  @SerializedName("numeroDocumentoIdentidad")
  private String numeroDocumentoIdentidad = null;

  @SerializedName("tipoDocumentoIdentidad")
  private Object tipoDocumentoIdentidad = null;

  public ClienteOutputModel contacto(ContactoOutputModel contacto) {
    this.contacto = contacto;
    return this;
  }

   /**
   * Get contacto
   * @return contacto
  **/
  @Schema(description = "")
  public ContactoOutputModel getContacto() {
    return contacto;
  }

  public void setContacto(ContactoOutputModel contacto) {
    this.contacto = contacto;
  }

  public ClienteOutputModel direccion(DireccionOutputModel direccion) {
    this.direccion = direccion;
    return this;
  }

   /**
   * Get direccion
   * @return direccion
  **/
  @Schema(description = "")
  public DireccionOutputModel getDireccion() {
    return direccion;
  }

  public void setDireccion(DireccionOutputModel direccion) {
    this.direccion = direccion;
  }

  public ClienteOutputModel nombre(String nombre) {
    this.nombre = nombre;
    return this;
  }

   /**
   * Get nombre
   * @return nombre
  **/
  @Schema(description = "")
  public String getNombre() {
    return nombre;
  }

  public void setNombre(String nombre) {
    this.nombre = nombre;
  }

  public ClienteOutputModel numeroDocumentoIdentidad(String numeroDocumentoIdentidad) {
    this.numeroDocumentoIdentidad = numeroDocumentoIdentidad;
    return this;
  }

   /**
   * Get numeroDocumentoIdentidad
   * @return numeroDocumentoIdentidad
  **/
  @Schema(description = "")
  public String getNumeroDocumentoIdentidad() {
    return numeroDocumentoIdentidad;
  }

  public void setNumeroDocumentoIdentidad(String numeroDocumentoIdentidad) {
    this.numeroDocumentoIdentidad = numeroDocumentoIdentidad;
  }

  public ClienteOutputModel tipoDocumentoIdentidad(Object tipoDocumentoIdentidad) {
    this.tipoDocumentoIdentidad = tipoDocumentoIdentidad;
    return this;
  }

   /**
   * Get tipoDocumentoIdentidad
   * @return tipoDocumentoIdentidad
  **/
  @Schema(required = true, description = "")
  public Object getTipoDocumentoIdentidad() {
    return tipoDocumentoIdentidad;
  }

  public void setTipoDocumentoIdentidad(Object tipoDocumentoIdentidad) {
    this.tipoDocumentoIdentidad = tipoDocumentoIdentidad;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ClienteOutputModel clienteOutputModel = (ClienteOutputModel) o;
    return Objects.equals(this.contacto, clienteOutputModel.contacto) &&
        Objects.equals(this.direccion, clienteOutputModel.direccion) &&
        Objects.equals(this.nombre, clienteOutputModel.nombre) &&
        Objects.equals(this.numeroDocumentoIdentidad, clienteOutputModel.numeroDocumentoIdentidad) &&
        Objects.equals(this.tipoDocumentoIdentidad, clienteOutputModel.tipoDocumentoIdentidad);
  }

  @Override
  public int hashCode() {
    return Objects.hash(contacto, direccion, nombre, numeroDocumentoIdentidad, tipoDocumentoIdentidad);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ClienteOutputModel {\n");
    
    sb.append("    contacto: ").append(toIndentedString(contacto)).append("\n");
    sb.append("    direccion: ").append(toIndentedString(direccion)).append("\n");
    sb.append("    nombre: ").append(toIndentedString(nombre)).append("\n");
    sb.append("    numeroDocumentoIdentidad: ").append(toIndentedString(numeroDocumentoIdentidad)).append("\n");
    sb.append("    tipoDocumentoIdentidad: ").append(toIndentedString(tipoDocumentoIdentidad)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
