/*
 * XML Builder API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0.Final
 * Contact: projectopenubl+subscribe@googlegroups.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * CreditNoteOutputModel
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-04-02T05:58:18.345Z[GMT]")
public class CreditNoteOutputModel {
  @SerializedName("cliente")
  private Object cliente = null;

  @SerializedName("detalle")
  private Object detalle = null;

  @SerializedName("fechaEmision")
  private String fechaEmision = null;

  @SerializedName("firmante")
  private Object firmante = null;

  @SerializedName("horaEmision")
  private String horaEmision = null;

  @SerializedName("impuestos")
  private Object impuestos = null;

  @SerializedName("moneda")
  private String moneda = null;

  @SerializedName("proveedor")
  private Object proveedor = null;

  @SerializedName("serieNumero")
  private String serieNumero = null;

  @SerializedName("totales")
  private Object totales = null;

  @SerializedName("descripcionSustentoDeNota")
  private String descripcionSustentoDeNota = null;

  @SerializedName("serieNumeroComprobanteAfectado")
  private String serieNumeroComprobanteAfectado = null;

  @SerializedName("tipoDocumentoComprobanteAfectado")
  private Object tipoDocumentoComprobanteAfectado = null;

  @SerializedName("tipoNota")
  private Object tipoNota = null;

  public CreditNoteOutputModel cliente(Object cliente) {
    this.cliente = cliente;
    return this;
  }

   /**
   * Get cliente
   * @return cliente
  **/
  @Schema(required = true, description = "")
  public Object getCliente() {
    return cliente;
  }

  public void setCliente(Object cliente) {
    this.cliente = cliente;
  }

  public CreditNoteOutputModel detalle(Object detalle) {
    this.detalle = detalle;
    return this;
  }

   /**
   * Get detalle
   * @return detalle
  **/
  @Schema(description = "")
  public Object getDetalle() {
    return detalle;
  }

  public void setDetalle(Object detalle) {
    this.detalle = detalle;
  }

  public CreditNoteOutputModel fechaEmision(String fechaEmision) {
    this.fechaEmision = fechaEmision;
    return this;
  }

   /**
   * Get fechaEmision
   * @return fechaEmision
  **/
  @Schema(description = "")
  public String getFechaEmision() {
    return fechaEmision;
  }

  public void setFechaEmision(String fechaEmision) {
    this.fechaEmision = fechaEmision;
  }

  public CreditNoteOutputModel firmante(Object firmante) {
    this.firmante = firmante;
    return this;
  }

   /**
   * Get firmante
   * @return firmante
  **/
  @Schema(required = true, description = "")
  public Object getFirmante() {
    return firmante;
  }

  public void setFirmante(Object firmante) {
    this.firmante = firmante;
  }

  public CreditNoteOutputModel horaEmision(String horaEmision) {
    this.horaEmision = horaEmision;
    return this;
  }

   /**
   * Get horaEmision
   * @return horaEmision
  **/
  @Schema(description = "")
  public String getHoraEmision() {
    return horaEmision;
  }

  public void setHoraEmision(String horaEmision) {
    this.horaEmision = horaEmision;
  }

  public CreditNoteOutputModel impuestos(Object impuestos) {
    this.impuestos = impuestos;
    return this;
  }

   /**
   * Get impuestos
   * @return impuestos
  **/
  @Schema(required = true, description = "")
  public Object getImpuestos() {
    return impuestos;
  }

  public void setImpuestos(Object impuestos) {
    this.impuestos = impuestos;
  }

  public CreditNoteOutputModel moneda(String moneda) {
    this.moneda = moneda;
    return this;
  }

   /**
   * Get moneda
   * @return moneda
  **/
  @Schema(description = "")
  public String getMoneda() {
    return moneda;
  }

  public void setMoneda(String moneda) {
    this.moneda = moneda;
  }

  public CreditNoteOutputModel proveedor(Object proveedor) {
    this.proveedor = proveedor;
    return this;
  }

   /**
   * Get proveedor
   * @return proveedor
  **/
  @Schema(required = true, description = "")
  public Object getProveedor() {
    return proveedor;
  }

  public void setProveedor(Object proveedor) {
    this.proveedor = proveedor;
  }

  public CreditNoteOutputModel serieNumero(String serieNumero) {
    this.serieNumero = serieNumero;
    return this;
  }

   /**
   * Get serieNumero
   * @return serieNumero
  **/
  @Schema(description = "")
  public String getSerieNumero() {
    return serieNumero;
  }

  public void setSerieNumero(String serieNumero) {
    this.serieNumero = serieNumero;
  }

  public CreditNoteOutputModel totales(Object totales) {
    this.totales = totales;
    return this;
  }

   /**
   * Get totales
   * @return totales
  **/
  @Schema(required = true, description = "")
  public Object getTotales() {
    return totales;
  }

  public void setTotales(Object totales) {
    this.totales = totales;
  }

  public CreditNoteOutputModel descripcionSustentoDeNota(String descripcionSustentoDeNota) {
    this.descripcionSustentoDeNota = descripcionSustentoDeNota;
    return this;
  }

   /**
   * Get descripcionSustentoDeNota
   * @return descripcionSustentoDeNota
  **/
  @Schema(description = "")
  public String getDescripcionSustentoDeNota() {
    return descripcionSustentoDeNota;
  }

  public void setDescripcionSustentoDeNota(String descripcionSustentoDeNota) {
    this.descripcionSustentoDeNota = descripcionSustentoDeNota;
  }

  public CreditNoteOutputModel serieNumeroComprobanteAfectado(String serieNumeroComprobanteAfectado) {
    this.serieNumeroComprobanteAfectado = serieNumeroComprobanteAfectado;
    return this;
  }

   /**
   * Get serieNumeroComprobanteAfectado
   * @return serieNumeroComprobanteAfectado
  **/
  @Schema(description = "")
  public String getSerieNumeroComprobanteAfectado() {
    return serieNumeroComprobanteAfectado;
  }

  public void setSerieNumeroComprobanteAfectado(String serieNumeroComprobanteAfectado) {
    this.serieNumeroComprobanteAfectado = serieNumeroComprobanteAfectado;
  }

  public CreditNoteOutputModel tipoDocumentoComprobanteAfectado(Object tipoDocumentoComprobanteAfectado) {
    this.tipoDocumentoComprobanteAfectado = tipoDocumentoComprobanteAfectado;
    return this;
  }

   /**
   * Get tipoDocumentoComprobanteAfectado
   * @return tipoDocumentoComprobanteAfectado
  **/
  @Schema(required = true, description = "")
  public Object getTipoDocumentoComprobanteAfectado() {
    return tipoDocumentoComprobanteAfectado;
  }

  public void setTipoDocumentoComprobanteAfectado(Object tipoDocumentoComprobanteAfectado) {
    this.tipoDocumentoComprobanteAfectado = tipoDocumentoComprobanteAfectado;
  }

  public CreditNoteOutputModel tipoNota(Object tipoNota) {
    this.tipoNota = tipoNota;
    return this;
  }

   /**
   * Get tipoNota
   * @return tipoNota
  **/
  @Schema(required = true, description = "")
  public Object getTipoNota() {
    return tipoNota;
  }

  public void setTipoNota(Object tipoNota) {
    this.tipoNota = tipoNota;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreditNoteOutputModel creditNoteOutputModel = (CreditNoteOutputModel) o;
    return Objects.equals(this.cliente, creditNoteOutputModel.cliente) &&
        Objects.equals(this.detalle, creditNoteOutputModel.detalle) &&
        Objects.equals(this.fechaEmision, creditNoteOutputModel.fechaEmision) &&
        Objects.equals(this.firmante, creditNoteOutputModel.firmante) &&
        Objects.equals(this.horaEmision, creditNoteOutputModel.horaEmision) &&
        Objects.equals(this.impuestos, creditNoteOutputModel.impuestos) &&
        Objects.equals(this.moneda, creditNoteOutputModel.moneda) &&
        Objects.equals(this.proveedor, creditNoteOutputModel.proveedor) &&
        Objects.equals(this.serieNumero, creditNoteOutputModel.serieNumero) &&
        Objects.equals(this.totales, creditNoteOutputModel.totales) &&
        Objects.equals(this.descripcionSustentoDeNota, creditNoteOutputModel.descripcionSustentoDeNota) &&
        Objects.equals(this.serieNumeroComprobanteAfectado, creditNoteOutputModel.serieNumeroComprobanteAfectado) &&
        Objects.equals(this.tipoDocumentoComprobanteAfectado, creditNoteOutputModel.tipoDocumentoComprobanteAfectado) &&
        Objects.equals(this.tipoNota, creditNoteOutputModel.tipoNota);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cliente, detalle, fechaEmision, firmante, horaEmision, impuestos, moneda, proveedor, serieNumero, totales, descripcionSustentoDeNota, serieNumeroComprobanteAfectado, tipoDocumentoComprobanteAfectado, tipoNota);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreditNoteOutputModel {\n");
    
    sb.append("    cliente: ").append(toIndentedString(cliente)).append("\n");
    sb.append("    detalle: ").append(toIndentedString(detalle)).append("\n");
    sb.append("    fechaEmision: ").append(toIndentedString(fechaEmision)).append("\n");
    sb.append("    firmante: ").append(toIndentedString(firmante)).append("\n");
    sb.append("    horaEmision: ").append(toIndentedString(horaEmision)).append("\n");
    sb.append("    impuestos: ").append(toIndentedString(impuestos)).append("\n");
    sb.append("    moneda: ").append(toIndentedString(moneda)).append("\n");
    sb.append("    proveedor: ").append(toIndentedString(proveedor)).append("\n");
    sb.append("    serieNumero: ").append(toIndentedString(serieNumero)).append("\n");
    sb.append("    totales: ").append(toIndentedString(totales)).append("\n");
    sb.append("    descripcionSustentoDeNota: ").append(toIndentedString(descripcionSustentoDeNota)).append("\n");
    sb.append("    serieNumeroComprobanteAfectado: ").append(toIndentedString(serieNumeroComprobanteAfectado)).append("\n");
    sb.append("    tipoDocumentoComprobanteAfectado: ").append(toIndentedString(tipoDocumentoComprobanteAfectado)).append("\n");
    sb.append("    tipoNota: ").append(toIndentedString(tipoNota)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
