/*
 * XML Builder API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0.Final
 * Contact: projectopenubl+subscribe@googlegroups.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * DireccionOutputModel
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-04-03T17:52:28.678Z[GMT]")
public class DireccionOutputModel {
  @SerializedName("codigoLocal")
  private String codigoLocal = null;

  @SerializedName("codigoPais")
  private String codigoPais = null;

  @SerializedName("departamento")
  private String departamento = null;

  @SerializedName("direccion")
  private String direccion = null;

  @SerializedName("distrito")
  private String distrito = null;

  @SerializedName("provincia")
  private String provincia = null;

  @SerializedName("ubigeo")
  private String ubigeo = null;

  @SerializedName("urbanizacion")
  private String urbanizacion = null;

  public DireccionOutputModel codigoLocal(String codigoLocal) {
    this.codigoLocal = codigoLocal;
    return this;
  }

   /**
   * Get codigoLocal
   * @return codigoLocal
  **/
  @Schema(description = "")
  public String getCodigoLocal() {
    return codigoLocal;
  }

  public void setCodigoLocal(String codigoLocal) {
    this.codigoLocal = codigoLocal;
  }

  public DireccionOutputModel codigoPais(String codigoPais) {
    this.codigoPais = codigoPais;
    return this;
  }

   /**
   * Get codigoPais
   * @return codigoPais
  **/
  @Schema(description = "")
  public String getCodigoPais() {
    return codigoPais;
  }

  public void setCodigoPais(String codigoPais) {
    this.codigoPais = codigoPais;
  }

  public DireccionOutputModel departamento(String departamento) {
    this.departamento = departamento;
    return this;
  }

   /**
   * Get departamento
   * @return departamento
  **/
  @Schema(description = "")
  public String getDepartamento() {
    return departamento;
  }

  public void setDepartamento(String departamento) {
    this.departamento = departamento;
  }

  public DireccionOutputModel direccion(String direccion) {
    this.direccion = direccion;
    return this;
  }

   /**
   * Get direccion
   * @return direccion
  **/
  @Schema(description = "")
  public String getDireccion() {
    return direccion;
  }

  public void setDireccion(String direccion) {
    this.direccion = direccion;
  }

  public DireccionOutputModel distrito(String distrito) {
    this.distrito = distrito;
    return this;
  }

   /**
   * Get distrito
   * @return distrito
  **/
  @Schema(description = "")
  public String getDistrito() {
    return distrito;
  }

  public void setDistrito(String distrito) {
    this.distrito = distrito;
  }

  public DireccionOutputModel provincia(String provincia) {
    this.provincia = provincia;
    return this;
  }

   /**
   * Get provincia
   * @return provincia
  **/
  @Schema(description = "")
  public String getProvincia() {
    return provincia;
  }

  public void setProvincia(String provincia) {
    this.provincia = provincia;
  }

  public DireccionOutputModel ubigeo(String ubigeo) {
    this.ubigeo = ubigeo;
    return this;
  }

   /**
   * Get ubigeo
   * @return ubigeo
  **/
  @Schema(description = "")
  public String getUbigeo() {
    return ubigeo;
  }

  public void setUbigeo(String ubigeo) {
    this.ubigeo = ubigeo;
  }

  public DireccionOutputModel urbanizacion(String urbanizacion) {
    this.urbanizacion = urbanizacion;
    return this;
  }

   /**
   * Get urbanizacion
   * @return urbanizacion
  **/
  @Schema(description = "")
  public String getUrbanizacion() {
    return urbanizacion;
  }

  public void setUrbanizacion(String urbanizacion) {
    this.urbanizacion = urbanizacion;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DireccionOutputModel direccionOutputModel = (DireccionOutputModel) o;
    return Objects.equals(this.codigoLocal, direccionOutputModel.codigoLocal) &&
        Objects.equals(this.codigoPais, direccionOutputModel.codigoPais) &&
        Objects.equals(this.departamento, direccionOutputModel.departamento) &&
        Objects.equals(this.direccion, direccionOutputModel.direccion) &&
        Objects.equals(this.distrito, direccionOutputModel.distrito) &&
        Objects.equals(this.provincia, direccionOutputModel.provincia) &&
        Objects.equals(this.ubigeo, direccionOutputModel.ubigeo) &&
        Objects.equals(this.urbanizacion, direccionOutputModel.urbanizacion);
  }

  @Override
  public int hashCode() {
    return Objects.hash(codigoLocal, codigoPais, departamento, direccion, distrito, provincia, ubigeo, urbanizacion);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DireccionOutputModel {\n");
    
    sb.append("    codigoLocal: ").append(toIndentedString(codigoLocal)).append("\n");
    sb.append("    codigoPais: ").append(toIndentedString(codigoPais)).append("\n");
    sb.append("    departamento: ").append(toIndentedString(departamento)).append("\n");
    sb.append("    direccion: ").append(toIndentedString(direccion)).append("\n");
    sb.append("    distrito: ").append(toIndentedString(distrito)).append("\n");
    sb.append("    provincia: ").append(toIndentedString(provincia)).append("\n");
    sb.append("    ubigeo: ").append(toIndentedString(ubigeo)).append("\n");
    sb.append("    urbanizacion: ").append(toIndentedString(urbanizacion)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
