/*
 * XML Builder API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0.Final
 * Contact: projectopenubl+subscribe@googlegroups.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * SummaryDocumentComprobanteOutputModel
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-04-03T17:52:28.678Z[GMT]")
public class SummaryDocumentComprobanteOutputModel {
  @SerializedName("cliente")
  private Object cliente = null;

  @SerializedName("impuestos")
  private Object impuestos = null;

  @SerializedName("serieNumero")
  private String serieNumero = null;

  @SerializedName("tipo")
  private Object tipo = null;

  @SerializedName("valorVenta")
  private Object valorVenta = null;

  public SummaryDocumentComprobanteOutputModel cliente(Object cliente) {
    this.cliente = cliente;
    return this;
  }

   /**
   * Get cliente
   * @return cliente
  **/
  @Schema(required = true, description = "")
  public Object getCliente() {
    return cliente;
  }

  public void setCliente(Object cliente) {
    this.cliente = cliente;
  }

  public SummaryDocumentComprobanteOutputModel impuestos(Object impuestos) {
    this.impuestos = impuestos;
    return this;
  }

   /**
   * Get impuestos
   * @return impuestos
  **/
  @Schema(required = true, description = "")
  public Object getImpuestos() {
    return impuestos;
  }

  public void setImpuestos(Object impuestos) {
    this.impuestos = impuestos;
  }

  public SummaryDocumentComprobanteOutputModel serieNumero(String serieNumero) {
    this.serieNumero = serieNumero;
    return this;
  }

   /**
   * Get serieNumero
   * @return serieNumero
  **/
  @Schema(description = "")
  public String getSerieNumero() {
    return serieNumero;
  }

  public void setSerieNumero(String serieNumero) {
    this.serieNumero = serieNumero;
  }

  public SummaryDocumentComprobanteOutputModel tipo(Object tipo) {
    this.tipo = tipo;
    return this;
  }

   /**
   * Get tipo
   * @return tipo
  **/
  @Schema(required = true, description = "")
  public Object getTipo() {
    return tipo;
  }

  public void setTipo(Object tipo) {
    this.tipo = tipo;
  }

  public SummaryDocumentComprobanteOutputModel valorVenta(Object valorVenta) {
    this.valorVenta = valorVenta;
    return this;
  }

   /**
   * Get valorVenta
   * @return valorVenta
  **/
  @Schema(required = true, description = "")
  public Object getValorVenta() {
    return valorVenta;
  }

  public void setValorVenta(Object valorVenta) {
    this.valorVenta = valorVenta;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SummaryDocumentComprobanteOutputModel summaryDocumentComprobanteOutputModel = (SummaryDocumentComprobanteOutputModel) o;
    return Objects.equals(this.cliente, summaryDocumentComprobanteOutputModel.cliente) &&
        Objects.equals(this.impuestos, summaryDocumentComprobanteOutputModel.impuestos) &&
        Objects.equals(this.serieNumero, summaryDocumentComprobanteOutputModel.serieNumero) &&
        Objects.equals(this.tipo, summaryDocumentComprobanteOutputModel.tipo) &&
        Objects.equals(this.valorVenta, summaryDocumentComprobanteOutputModel.valorVenta);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cliente, impuestos, serieNumero, tipo, valorVenta);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SummaryDocumentComprobanteOutputModel {\n");
    
    sb.append("    cliente: ").append(toIndentedString(cliente)).append("\n");
    sb.append("    impuestos: ").append(toIndentedString(impuestos)).append("\n");
    sb.append("    serieNumero: ").append(toIndentedString(serieNumero)).append("\n");
    sb.append("    tipo: ").append(toIndentedString(tipo)).append("\n");
    sb.append("    valorVenta: ").append(toIndentedString(valorVenta)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
