/*
 * XML Builder API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0.Final
 * Contact: projectopenubl+subscribe@googlegroups.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * SummaryDocumentLineComprobante
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-04-02T05:58:18.345Z[GMT]")
public class SummaryDocumentLineComprobante {
  @SerializedName("cliente")
  private Object cliente = null;

  @SerializedName("impuestos")
  private Object impuestos = null;

  @SerializedName("serieNumero")
  private String serieNumero = null;

  /**
   * Catalog 01
   */
  @JsonAdapter(TipoEnum.Adapter.class)
  public enum TipoEnum {
    FACTURA("FACTURA"),
    _01("01"),
    BOLETA("BOLETA"),
    _03("03"),
    NOTA_CREDITO("NOTA_CREDITO"),
    _07("07"),
    NOTA_DEBITO("NOTA_DEBITO"),
    _08("08");

    private String value;

    TipoEnum(String value) {
      this.value = value;
    }
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    public static TipoEnum fromValue(String text) {
      for (TipoEnum b : TipoEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
    public static class Adapter extends TypeAdapter<TipoEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final TipoEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public TipoEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return TipoEnum.fromValue(String.valueOf(value));
      }
    }
  }  @SerializedName("tipo")
  private TipoEnum tipo = null;

  @SerializedName("valorVenta")
  private Object valorVenta = null;

  public SummaryDocumentLineComprobante cliente(Object cliente) {
    this.cliente = cliente;
    return this;
  }

   /**
   * Get cliente
   * @return cliente
  **/
  @Schema(required = true, description = "")
  public Object getCliente() {
    return cliente;
  }

  public void setCliente(Object cliente) {
    this.cliente = cliente;
  }

  public SummaryDocumentLineComprobante impuestos(Object impuestos) {
    this.impuestos = impuestos;
    return this;
  }

   /**
   * Get impuestos
   * @return impuestos
  **/
  @Schema(required = true, description = "")
  public Object getImpuestos() {
    return impuestos;
  }

  public void setImpuestos(Object impuestos) {
    this.impuestos = impuestos;
  }

  public SummaryDocumentLineComprobante serieNumero(String serieNumero) {
    this.serieNumero = serieNumero;
    return this;
  }

   /**
   * Get serieNumero
   * @return serieNumero
  **/
  @Schema(example = "BC001-1", description = "")
  public String getSerieNumero() {
    return serieNumero;
  }

  public void setSerieNumero(String serieNumero) {
    this.serieNumero = serieNumero;
  }

  public SummaryDocumentLineComprobante tipo(TipoEnum tipo) {
    this.tipo = tipo;
    return this;
  }

   /**
   * Catalog 01
   * @return tipo
  **/
  @Schema(example = "NOTA_CREDITO", required = true, description = "Catalog 01")
  public TipoEnum getTipo() {
    return tipo;
  }

  public void setTipo(TipoEnum tipo) {
    this.tipo = tipo;
  }

  public SummaryDocumentLineComprobante valorVenta(Object valorVenta) {
    this.valorVenta = valorVenta;
    return this;
  }

   /**
   * Get valorVenta
   * @return valorVenta
  **/
  @Schema(required = true, description = "")
  public Object getValorVenta() {
    return valorVenta;
  }

  public void setValorVenta(Object valorVenta) {
    this.valorVenta = valorVenta;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SummaryDocumentLineComprobante summaryDocumentLineComprobante = (SummaryDocumentLineComprobante) o;
    return Objects.equals(this.cliente, summaryDocumentLineComprobante.cliente) &&
        Objects.equals(this.impuestos, summaryDocumentLineComprobante.impuestos) &&
        Objects.equals(this.serieNumero, summaryDocumentLineComprobante.serieNumero) &&
        Objects.equals(this.tipo, summaryDocumentLineComprobante.tipo) &&
        Objects.equals(this.valorVenta, summaryDocumentLineComprobante.valorVenta);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cliente, impuestos, serieNumero, tipo, valorVenta);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SummaryDocumentLineComprobante {\n");
    
    sb.append("    cliente: ").append(toIndentedString(cliente)).append("\n");
    sb.append("    impuestos: ").append(toIndentedString(impuestos)).append("\n");
    sb.append("    serieNumero: ").append(toIndentedString(serieNumero)).append("\n");
    sb.append("    tipo: ").append(toIndentedString(tipo)).append("\n");
    sb.append("    valorVenta: ").append(toIndentedString(valorVenta)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
