/*
 * XML Builder API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0.Final
 * Contact: projectopenubl+subscribe@googlegroups.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * VoidedDocumentOutputModel
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-04-03T17:52:28.678Z[GMT]")
public class VoidedDocumentOutputModel {
  @SerializedName("comprobante")
  private Object comprobante = null;

  @SerializedName("descripcionSustento")
  private String descripcionSustento = null;

  @SerializedName("fechaEmision")
  private String fechaEmision = null;

  @SerializedName("firmante")
  private Object firmante = null;

  @SerializedName("proveedor")
  private Object proveedor = null;

  @SerializedName("serieNumero")
  private String serieNumero = null;

  public VoidedDocumentOutputModel comprobante(Object comprobante) {
    this.comprobante = comprobante;
    return this;
  }

   /**
   * Get comprobante
   * @return comprobante
  **/
  @Schema(required = true, description = "")
  public Object getComprobante() {
    return comprobante;
  }

  public void setComprobante(Object comprobante) {
    this.comprobante = comprobante;
  }

  public VoidedDocumentOutputModel descripcionSustento(String descripcionSustento) {
    this.descripcionSustento = descripcionSustento;
    return this;
  }

   /**
   * Get descripcionSustento
   * @return descripcionSustento
  **/
  @Schema(description = "")
  public String getDescripcionSustento() {
    return descripcionSustento;
  }

  public void setDescripcionSustento(String descripcionSustento) {
    this.descripcionSustento = descripcionSustento;
  }

  public VoidedDocumentOutputModel fechaEmision(String fechaEmision) {
    this.fechaEmision = fechaEmision;
    return this;
  }

   /**
   * Get fechaEmision
   * @return fechaEmision
  **/
  @Schema(description = "")
  public String getFechaEmision() {
    return fechaEmision;
  }

  public void setFechaEmision(String fechaEmision) {
    this.fechaEmision = fechaEmision;
  }

  public VoidedDocumentOutputModel firmante(Object firmante) {
    this.firmante = firmante;
    return this;
  }

   /**
   * Get firmante
   * @return firmante
  **/
  @Schema(required = true, description = "")
  public Object getFirmante() {
    return firmante;
  }

  public void setFirmante(Object firmante) {
    this.firmante = firmante;
  }

  public VoidedDocumentOutputModel proveedor(Object proveedor) {
    this.proveedor = proveedor;
    return this;
  }

   /**
   * Get proveedor
   * @return proveedor
  **/
  @Schema(required = true, description = "")
  public Object getProveedor() {
    return proveedor;
  }

  public void setProveedor(Object proveedor) {
    this.proveedor = proveedor;
  }

  public VoidedDocumentOutputModel serieNumero(String serieNumero) {
    this.serieNumero = serieNumero;
    return this;
  }

   /**
   * Get serieNumero
   * @return serieNumero
  **/
  @Schema(description = "")
  public String getSerieNumero() {
    return serieNumero;
  }

  public void setSerieNumero(String serieNumero) {
    this.serieNumero = serieNumero;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VoidedDocumentOutputModel voidedDocumentOutputModel = (VoidedDocumentOutputModel) o;
    return Objects.equals(this.comprobante, voidedDocumentOutputModel.comprobante) &&
        Objects.equals(this.descripcionSustento, voidedDocumentOutputModel.descripcionSustento) &&
        Objects.equals(this.fechaEmision, voidedDocumentOutputModel.fechaEmision) &&
        Objects.equals(this.firmante, voidedDocumentOutputModel.firmante) &&
        Objects.equals(this.proveedor, voidedDocumentOutputModel.proveedor) &&
        Objects.equals(this.serieNumero, voidedDocumentOutputModel.serieNumero);
  }

  @Override
  public int hashCode() {
    return Objects.hash(comprobante, descripcionSustento, fechaEmision, firmante, proveedor, serieNumero);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VoidedDocumentOutputModel {\n");
    
    sb.append("    comprobante: ").append(toIndentedString(comprobante)).append("\n");
    sb.append("    descripcionSustento: ").append(toIndentedString(descripcionSustento)).append("\n");
    sb.append("    fechaEmision: ").append(toIndentedString(fechaEmision)).append("\n");
    sb.append("    firmante: ").append(toIndentedString(firmante)).append("\n");
    sb.append("    proveedor: ").append(toIndentedString(proveedor)).append("\n");
    sb.append("    serieNumero: ").append(toIndentedString(serieNumero)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
