/*
 * XML Builder API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0.Final
 * Contact: projectopenubl+subscribe@googlegroups.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * VoidedDocumentLineOutputModel
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-04-03T17:52:28.678Z[GMT]")
public class VoidedDocumentLineOutputModel {
  @SerializedName("fechaEmision")
  private String fechaEmision = null;

  @SerializedName("numero")
  private String numero = null;

  @SerializedName("serie")
  private String serie = null;

  @SerializedName("tipoComprobante")
  private Object tipoComprobante = null;

  public VoidedDocumentLineOutputModel fechaEmision(String fechaEmision) {
    this.fechaEmision = fechaEmision;
    return this;
  }

   /**
   * Get fechaEmision
   * @return fechaEmision
  **/
  @Schema(description = "")
  public String getFechaEmision() {
    return fechaEmision;
  }

  public void setFechaEmision(String fechaEmision) {
    this.fechaEmision = fechaEmision;
  }

  public VoidedDocumentLineOutputModel numero(String numero) {
    this.numero = numero;
    return this;
  }

   /**
   * Get numero
   * @return numero
  **/
  @Schema(description = "")
  public String getNumero() {
    return numero;
  }

  public void setNumero(String numero) {
    this.numero = numero;
  }

  public VoidedDocumentLineOutputModel serie(String serie) {
    this.serie = serie;
    return this;
  }

   /**
   * Get serie
   * @return serie
  **/
  @Schema(description = "")
  public String getSerie() {
    return serie;
  }

  public void setSerie(String serie) {
    this.serie = serie;
  }

  public VoidedDocumentLineOutputModel tipoComprobante(Object tipoComprobante) {
    this.tipoComprobante = tipoComprobante;
    return this;
  }

   /**
   * Get tipoComprobante
   * @return tipoComprobante
  **/
  @Schema(required = true, description = "")
  public Object getTipoComprobante() {
    return tipoComprobante;
  }

  public void setTipoComprobante(Object tipoComprobante) {
    this.tipoComprobante = tipoComprobante;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VoidedDocumentLineOutputModel voidedDocumentLineOutputModel = (VoidedDocumentLineOutputModel) o;
    return Objects.equals(this.fechaEmision, voidedDocumentLineOutputModel.fechaEmision) &&
        Objects.equals(this.numero, voidedDocumentLineOutputModel.numero) &&
        Objects.equals(this.serie, voidedDocumentLineOutputModel.serie) &&
        Objects.equals(this.tipoComprobante, voidedDocumentLineOutputModel.tipoComprobante);
  }

  @Override
  public int hashCode() {
    return Objects.hash(fechaEmision, numero, serie, tipoComprobante);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VoidedDocumentLineOutputModel {\n");
    
    sb.append("    fechaEmision: ").append(toIndentedString(fechaEmision)).append("\n");
    sb.append("    numero: ").append(toIndentedString(numero)).append("\n");
    sb.append("    serie: ").append(toIndentedString(serie)).append("\n");
    sb.append("    tipoComprobante: ").append(toIndentedString(tipoComprobante)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
