/* 
 * XML Builder API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0.Final
 * Contact: projectopenubl+subscribe@googlegroups.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing CreateApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class CreateApiTests
    {
        private CreateApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new CreateApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CreateApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' CreateApi
            //Assert.IsInstanceOfType(typeof(CreateApi), instance, "instance is a CreateApi");
        }

        /// <summary>
        /// Test ApiDocumentsCreditNoteCreatePost
        /// </summary>
        [Test]
        public void ApiDocumentsCreditNoteCreatePostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CreditNote body = null;
            //var response = instance.ApiDocumentsCreditNoteCreatePost(body);
            //Assert.IsInstanceOf<string> (response, "response is string");
        }
        /// <summary>
        /// Test ApiDocumentsDebitNoteCreatePost
        /// </summary>
        [Test]
        public void ApiDocumentsDebitNoteCreatePostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //DebitNote body = null;
            //var response = instance.ApiDocumentsDebitNoteCreatePost(body);
            //Assert.IsInstanceOf<string> (response, "response is string");
        }
        /// <summary>
        /// Test ApiDocumentsInvoiceCreatePost
        /// </summary>
        [Test]
        public void ApiDocumentsInvoiceCreatePostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Invoice body = null;
            //var response = instance.ApiDocumentsInvoiceCreatePost(body);
            //Assert.IsInstanceOf<string> (response, "response is string");
        }
        /// <summary>
        /// Test ApiDocumentsSummaryDocumentCreatePost
        /// </summary>
        [Test]
        public void ApiDocumentsSummaryDocumentCreatePostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //SummaryDocument body = null;
            //var response = instance.ApiDocumentsSummaryDocumentCreatePost(body);
            //Assert.IsInstanceOf<string> (response, "response is string");
        }
        /// <summary>
        /// Test ApiDocumentsVoidedDocumentCreatePost
        /// </summary>
        [Test]
        public void ApiDocumentsVoidedDocumentCreatePostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //VoidedDocument body = null;
            //var response = instance.ApiDocumentsVoidedDocumentCreatePost(body);
            //Assert.IsInstanceOf<string> (response, "response is string");
        }
    }

}
