# coding: utf-8

"""
    XML Builder API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0.Final
    Contact: projectopenubl+subscribe@googlegroups.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class DebitNoteOutputModel(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'cliente': 'Object',
        'detalle': 'Object',
        'fecha_emision': 'str',
        'firmante': 'Object',
        'hora_emision': 'str',
        'impuestos': 'Object',
        'moneda': 'str',
        'proveedor': 'Object',
        'serie_numero': 'str',
        'totales': 'Object',
        'descripcion_sustento_de_nota': 'str',
        'serie_numero_comprobante_afectado': 'str',
        'tipo_documento_comprobante_afectado': 'Object',
        'tipo_nota': 'Object'
    }

    attribute_map = {
        'cliente': 'cliente',
        'detalle': 'detalle',
        'fecha_emision': 'fechaEmision',
        'firmante': 'firmante',
        'hora_emision': 'horaEmision',
        'impuestos': 'impuestos',
        'moneda': 'moneda',
        'proveedor': 'proveedor',
        'serie_numero': 'serieNumero',
        'totales': 'totales',
        'descripcion_sustento_de_nota': 'descripcionSustentoDeNota',
        'serie_numero_comprobante_afectado': 'serieNumeroComprobanteAfectado',
        'tipo_documento_comprobante_afectado': 'tipoDocumentoComprobanteAfectado',
        'tipo_nota': 'tipoNota'
    }

    def __init__(self, cliente=None, detalle=None, fecha_emision=None, firmante=None, hora_emision=None, impuestos=None, moneda=None, proveedor=None, serie_numero=None, totales=None, descripcion_sustento_de_nota=None, serie_numero_comprobante_afectado=None, tipo_documento_comprobante_afectado=None, tipo_nota=None):  # noqa: E501
        """DebitNoteOutputModel - a model defined in Swagger"""  # noqa: E501
        self._cliente = None
        self._detalle = None
        self._fecha_emision = None
        self._firmante = None
        self._hora_emision = None
        self._impuestos = None
        self._moneda = None
        self._proveedor = None
        self._serie_numero = None
        self._totales = None
        self._descripcion_sustento_de_nota = None
        self._serie_numero_comprobante_afectado = None
        self._tipo_documento_comprobante_afectado = None
        self._tipo_nota = None
        self.discriminator = None
        self.cliente = cliente
        if detalle is not None:
            self.detalle = detalle
        if fecha_emision is not None:
            self.fecha_emision = fecha_emision
        self.firmante = firmante
        if hora_emision is not None:
            self.hora_emision = hora_emision
        self.impuestos = impuestos
        if moneda is not None:
            self.moneda = moneda
        self.proveedor = proveedor
        if serie_numero is not None:
            self.serie_numero = serie_numero
        self.totales = totales
        if descripcion_sustento_de_nota is not None:
            self.descripcion_sustento_de_nota = descripcion_sustento_de_nota
        if serie_numero_comprobante_afectado is not None:
            self.serie_numero_comprobante_afectado = serie_numero_comprobante_afectado
        self.tipo_documento_comprobante_afectado = tipo_documento_comprobante_afectado
        self.tipo_nota = tipo_nota

    @property
    def cliente(self):
        """Gets the cliente of this DebitNoteOutputModel.  # noqa: E501


        :return: The cliente of this DebitNoteOutputModel.  # noqa: E501
        :rtype: Object
        """
        return self._cliente

    @cliente.setter
    def cliente(self, cliente):
        """Sets the cliente of this DebitNoteOutputModel.


        :param cliente: The cliente of this DebitNoteOutputModel.  # noqa: E501
        :type: Object
        """
        if cliente is None:
            raise ValueError("Invalid value for `cliente`, must not be `None`")  # noqa: E501

        self._cliente = cliente

    @property
    def detalle(self):
        """Gets the detalle of this DebitNoteOutputModel.  # noqa: E501


        :return: The detalle of this DebitNoteOutputModel.  # noqa: E501
        :rtype: Object
        """
        return self._detalle

    @detalle.setter
    def detalle(self, detalle):
        """Sets the detalle of this DebitNoteOutputModel.


        :param detalle: The detalle of this DebitNoteOutputModel.  # noqa: E501
        :type: Object
        """

        self._detalle = detalle

    @property
    def fecha_emision(self):
        """Gets the fecha_emision of this DebitNoteOutputModel.  # noqa: E501


        :return: The fecha_emision of this DebitNoteOutputModel.  # noqa: E501
        :rtype: str
        """
        return self._fecha_emision

    @fecha_emision.setter
    def fecha_emision(self, fecha_emision):
        """Sets the fecha_emision of this DebitNoteOutputModel.


        :param fecha_emision: The fecha_emision of this DebitNoteOutputModel.  # noqa: E501
        :type: str
        """

        self._fecha_emision = fecha_emision

    @property
    def firmante(self):
        """Gets the firmante of this DebitNoteOutputModel.  # noqa: E501


        :return: The firmante of this DebitNoteOutputModel.  # noqa: E501
        :rtype: Object
        """
        return self._firmante

    @firmante.setter
    def firmante(self, firmante):
        """Sets the firmante of this DebitNoteOutputModel.


        :param firmante: The firmante of this DebitNoteOutputModel.  # noqa: E501
        :type: Object
        """
        if firmante is None:
            raise ValueError("Invalid value for `firmante`, must not be `None`")  # noqa: E501

        self._firmante = firmante

    @property
    def hora_emision(self):
        """Gets the hora_emision of this DebitNoteOutputModel.  # noqa: E501


        :return: The hora_emision of this DebitNoteOutputModel.  # noqa: E501
        :rtype: str
        """
        return self._hora_emision

    @hora_emision.setter
    def hora_emision(self, hora_emision):
        """Sets the hora_emision of this DebitNoteOutputModel.


        :param hora_emision: The hora_emision of this DebitNoteOutputModel.  # noqa: E501
        :type: str
        """

        self._hora_emision = hora_emision

    @property
    def impuestos(self):
        """Gets the impuestos of this DebitNoteOutputModel.  # noqa: E501


        :return: The impuestos of this DebitNoteOutputModel.  # noqa: E501
        :rtype: Object
        """
        return self._impuestos

    @impuestos.setter
    def impuestos(self, impuestos):
        """Sets the impuestos of this DebitNoteOutputModel.


        :param impuestos: The impuestos of this DebitNoteOutputModel.  # noqa: E501
        :type: Object
        """
        if impuestos is None:
            raise ValueError("Invalid value for `impuestos`, must not be `None`")  # noqa: E501

        self._impuestos = impuestos

    @property
    def moneda(self):
        """Gets the moneda of this DebitNoteOutputModel.  # noqa: E501


        :return: The moneda of this DebitNoteOutputModel.  # noqa: E501
        :rtype: str
        """
        return self._moneda

    @moneda.setter
    def moneda(self, moneda):
        """Sets the moneda of this DebitNoteOutputModel.


        :param moneda: The moneda of this DebitNoteOutputModel.  # noqa: E501
        :type: str
        """

        self._moneda = moneda

    @property
    def proveedor(self):
        """Gets the proveedor of this DebitNoteOutputModel.  # noqa: E501


        :return: The proveedor of this DebitNoteOutputModel.  # noqa: E501
        :rtype: Object
        """
        return self._proveedor

    @proveedor.setter
    def proveedor(self, proveedor):
        """Sets the proveedor of this DebitNoteOutputModel.


        :param proveedor: The proveedor of this DebitNoteOutputModel.  # noqa: E501
        :type: Object
        """
        if proveedor is None:
            raise ValueError("Invalid value for `proveedor`, must not be `None`")  # noqa: E501

        self._proveedor = proveedor

    @property
    def serie_numero(self):
        """Gets the serie_numero of this DebitNoteOutputModel.  # noqa: E501


        :return: The serie_numero of this DebitNoteOutputModel.  # noqa: E501
        :rtype: str
        """
        return self._serie_numero

    @serie_numero.setter
    def serie_numero(self, serie_numero):
        """Sets the serie_numero of this DebitNoteOutputModel.


        :param serie_numero: The serie_numero of this DebitNoteOutputModel.  # noqa: E501
        :type: str
        """

        self._serie_numero = serie_numero

    @property
    def totales(self):
        """Gets the totales of this DebitNoteOutputModel.  # noqa: E501


        :return: The totales of this DebitNoteOutputModel.  # noqa: E501
        :rtype: Object
        """
        return self._totales

    @totales.setter
    def totales(self, totales):
        """Sets the totales of this DebitNoteOutputModel.


        :param totales: The totales of this DebitNoteOutputModel.  # noqa: E501
        :type: Object
        """
        if totales is None:
            raise ValueError("Invalid value for `totales`, must not be `None`")  # noqa: E501

        self._totales = totales

    @property
    def descripcion_sustento_de_nota(self):
        """Gets the descripcion_sustento_de_nota of this DebitNoteOutputModel.  # noqa: E501


        :return: The descripcion_sustento_de_nota of this DebitNoteOutputModel.  # noqa: E501
        :rtype: str
        """
        return self._descripcion_sustento_de_nota

    @descripcion_sustento_de_nota.setter
    def descripcion_sustento_de_nota(self, descripcion_sustento_de_nota):
        """Sets the descripcion_sustento_de_nota of this DebitNoteOutputModel.


        :param descripcion_sustento_de_nota: The descripcion_sustento_de_nota of this DebitNoteOutputModel.  # noqa: E501
        :type: str
        """

        self._descripcion_sustento_de_nota = descripcion_sustento_de_nota

    @property
    def serie_numero_comprobante_afectado(self):
        """Gets the serie_numero_comprobante_afectado of this DebitNoteOutputModel.  # noqa: E501


        :return: The serie_numero_comprobante_afectado of this DebitNoteOutputModel.  # noqa: E501
        :rtype: str
        """
        return self._serie_numero_comprobante_afectado

    @serie_numero_comprobante_afectado.setter
    def serie_numero_comprobante_afectado(self, serie_numero_comprobante_afectado):
        """Sets the serie_numero_comprobante_afectado of this DebitNoteOutputModel.


        :param serie_numero_comprobante_afectado: The serie_numero_comprobante_afectado of this DebitNoteOutputModel.  # noqa: E501
        :type: str
        """

        self._serie_numero_comprobante_afectado = serie_numero_comprobante_afectado

    @property
    def tipo_documento_comprobante_afectado(self):
        """Gets the tipo_documento_comprobante_afectado of this DebitNoteOutputModel.  # noqa: E501


        :return: The tipo_documento_comprobante_afectado of this DebitNoteOutputModel.  # noqa: E501
        :rtype: Object
        """
        return self._tipo_documento_comprobante_afectado

    @tipo_documento_comprobante_afectado.setter
    def tipo_documento_comprobante_afectado(self, tipo_documento_comprobante_afectado):
        """Sets the tipo_documento_comprobante_afectado of this DebitNoteOutputModel.


        :param tipo_documento_comprobante_afectado: The tipo_documento_comprobante_afectado of this DebitNoteOutputModel.  # noqa: E501
        :type: Object
        """
        if tipo_documento_comprobante_afectado is None:
            raise ValueError("Invalid value for `tipo_documento_comprobante_afectado`, must not be `None`")  # noqa: E501

        self._tipo_documento_comprobante_afectado = tipo_documento_comprobante_afectado

    @property
    def tipo_nota(self):
        """Gets the tipo_nota of this DebitNoteOutputModel.  # noqa: E501


        :return: The tipo_nota of this DebitNoteOutputModel.  # noqa: E501
        :rtype: Object
        """
        return self._tipo_nota

    @tipo_nota.setter
    def tipo_nota(self, tipo_nota):
        """Sets the tipo_nota of this DebitNoteOutputModel.


        :param tipo_nota: The tipo_nota of this DebitNoteOutputModel.  # noqa: E501
        :type: Object
        """
        if tipo_nota is None:
            raise ValueError("Invalid value for `tipo_nota`, must not be `None`")  # noqa: E501

        self._tipo_nota = tipo_nota

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DebitNoteOutputModel, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DebitNoteOutputModel):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
