# coding: utf-8

"""
    XML Builder API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0.Final
    Contact: projectopenubl+subscribe@googlegroups.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class SummaryDocumentOutputModel(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'detalle': 'Object',
        'fecha_emision': 'str',
        'fecha_emision_de_comprobantes_asociados': 'str',
        'firmante': 'Object',
        'moneda': 'str',
        'proveedor': 'Object',
        'serie_numero': 'str'
    }

    attribute_map = {
        'detalle': 'detalle',
        'fecha_emision': 'fechaEmision',
        'fecha_emision_de_comprobantes_asociados': 'fechaEmisionDeComprobantesAsociados',
        'firmante': 'firmante',
        'moneda': 'moneda',
        'proveedor': 'proveedor',
        'serie_numero': 'serieNumero'
    }

    def __init__(self, detalle=None, fecha_emision=None, fecha_emision_de_comprobantes_asociados=None, firmante=None, moneda=None, proveedor=None, serie_numero=None):  # noqa: E501
        """SummaryDocumentOutputModel - a model defined in Swagger"""  # noqa: E501
        self._detalle = None
        self._fecha_emision = None
        self._fecha_emision_de_comprobantes_asociados = None
        self._firmante = None
        self._moneda = None
        self._proveedor = None
        self._serie_numero = None
        self.discriminator = None
        self.detalle = detalle
        if fecha_emision is not None:
            self.fecha_emision = fecha_emision
        if fecha_emision_de_comprobantes_asociados is not None:
            self.fecha_emision_de_comprobantes_asociados = fecha_emision_de_comprobantes_asociados
        self.firmante = firmante
        if moneda is not None:
            self.moneda = moneda
        self.proveedor = proveedor
        if serie_numero is not None:
            self.serie_numero = serie_numero

    @property
    def detalle(self):
        """Gets the detalle of this SummaryDocumentOutputModel.  # noqa: E501


        :return: The detalle of this SummaryDocumentOutputModel.  # noqa: E501
        :rtype: Object
        """
        return self._detalle

    @detalle.setter
    def detalle(self, detalle):
        """Sets the detalle of this SummaryDocumentOutputModel.


        :param detalle: The detalle of this SummaryDocumentOutputModel.  # noqa: E501
        :type: Object
        """
        if detalle is None:
            raise ValueError("Invalid value for `detalle`, must not be `None`")  # noqa: E501

        self._detalle = detalle

    @property
    def fecha_emision(self):
        """Gets the fecha_emision of this SummaryDocumentOutputModel.  # noqa: E501


        :return: The fecha_emision of this SummaryDocumentOutputModel.  # noqa: E501
        :rtype: str
        """
        return self._fecha_emision

    @fecha_emision.setter
    def fecha_emision(self, fecha_emision):
        """Sets the fecha_emision of this SummaryDocumentOutputModel.


        :param fecha_emision: The fecha_emision of this SummaryDocumentOutputModel.  # noqa: E501
        :type: str
        """

        self._fecha_emision = fecha_emision

    @property
    def fecha_emision_de_comprobantes_asociados(self):
        """Gets the fecha_emision_de_comprobantes_asociados of this SummaryDocumentOutputModel.  # noqa: E501


        :return: The fecha_emision_de_comprobantes_asociados of this SummaryDocumentOutputModel.  # noqa: E501
        :rtype: str
        """
        return self._fecha_emision_de_comprobantes_asociados

    @fecha_emision_de_comprobantes_asociados.setter
    def fecha_emision_de_comprobantes_asociados(self, fecha_emision_de_comprobantes_asociados):
        """Sets the fecha_emision_de_comprobantes_asociados of this SummaryDocumentOutputModel.


        :param fecha_emision_de_comprobantes_asociados: The fecha_emision_de_comprobantes_asociados of this SummaryDocumentOutputModel.  # noqa: E501
        :type: str
        """

        self._fecha_emision_de_comprobantes_asociados = fecha_emision_de_comprobantes_asociados

    @property
    def firmante(self):
        """Gets the firmante of this SummaryDocumentOutputModel.  # noqa: E501


        :return: The firmante of this SummaryDocumentOutputModel.  # noqa: E501
        :rtype: Object
        """
        return self._firmante

    @firmante.setter
    def firmante(self, firmante):
        """Sets the firmante of this SummaryDocumentOutputModel.


        :param firmante: The firmante of this SummaryDocumentOutputModel.  # noqa: E501
        :type: Object
        """
        if firmante is None:
            raise ValueError("Invalid value for `firmante`, must not be `None`")  # noqa: E501

        self._firmante = firmante

    @property
    def moneda(self):
        """Gets the moneda of this SummaryDocumentOutputModel.  # noqa: E501


        :return: The moneda of this SummaryDocumentOutputModel.  # noqa: E501
        :rtype: str
        """
        return self._moneda

    @moneda.setter
    def moneda(self, moneda):
        """Sets the moneda of this SummaryDocumentOutputModel.


        :param moneda: The moneda of this SummaryDocumentOutputModel.  # noqa: E501
        :type: str
        """

        self._moneda = moneda

    @property
    def proveedor(self):
        """Gets the proveedor of this SummaryDocumentOutputModel.  # noqa: E501


        :return: The proveedor of this SummaryDocumentOutputModel.  # noqa: E501
        :rtype: Object
        """
        return self._proveedor

    @proveedor.setter
    def proveedor(self, proveedor):
        """Sets the proveedor of this SummaryDocumentOutputModel.


        :param proveedor: The proveedor of this SummaryDocumentOutputModel.  # noqa: E501
        :type: Object
        """
        if proveedor is None:
            raise ValueError("Invalid value for `proveedor`, must not be `None`")  # noqa: E501

        self._proveedor = proveedor

    @property
    def serie_numero(self):
        """Gets the serie_numero of this SummaryDocumentOutputModel.  # noqa: E501


        :return: The serie_numero of this SummaryDocumentOutputModel.  # noqa: E501
        :rtype: str
        """
        return self._serie_numero

    @serie_numero.setter
    def serie_numero(self, serie_numero):
        """Sets the serie_numero of this SummaryDocumentOutputModel.


        :param serie_numero: The serie_numero of this SummaryDocumentOutputModel.  # noqa: E501
        :type: str
        """

        self._serie_numero = serie_numero

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SummaryDocumentOutputModel, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SummaryDocumentOutputModel):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
