# coding: utf-8

"""
    XML Builder API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0.Final
    Contact: projectopenubl+subscribe@googlegroups.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class SummaryDocument(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'detalle': 'Object',
        'fecha_emision': 'int',
        'fecha_emision_de_comprobantes_asociados': 'int',
        'firmante': 'Firmante',
        'numero': 'int',
        'proveedor': 'Object'
    }

    attribute_map = {
        'detalle': 'detalle',
        'fecha_emision': 'fechaEmision',
        'fecha_emision_de_comprobantes_asociados': 'fechaEmisionDeComprobantesAsociados',
        'firmante': 'firmante',
        'numero': 'numero',
        'proveedor': 'proveedor'
    }

    def __init__(self, detalle=None, fecha_emision=None, fecha_emision_de_comprobantes_asociados=None, firmante=None, numero=None, proveedor=None):  # noqa: E501
        """SummaryDocument - a model defined in Swagger"""  # noqa: E501
        self._detalle = None
        self._fecha_emision = None
        self._fecha_emision_de_comprobantes_asociados = None
        self._firmante = None
        self._numero = None
        self._proveedor = None
        self.discriminator = None
        self.detalle = detalle
        if fecha_emision is not None:
            self.fecha_emision = fecha_emision
        self.fecha_emision_de_comprobantes_asociados = fecha_emision_de_comprobantes_asociados
        if firmante is not None:
            self.firmante = firmante
        self.numero = numero
        self.proveedor = proveedor

    @property
    def detalle(self):
        """Gets the detalle of this SummaryDocument.  # noqa: E501


        :return: The detalle of this SummaryDocument.  # noqa: E501
        :rtype: Object
        """
        return self._detalle

    @detalle.setter
    def detalle(self, detalle):
        """Sets the detalle of this SummaryDocument.


        :param detalle: The detalle of this SummaryDocument.  # noqa: E501
        :type: Object
        """
        if detalle is None:
            raise ValueError("Invalid value for `detalle`, must not be `None`")  # noqa: E501

        self._detalle = detalle

    @property
    def fecha_emision(self):
        """Gets the fecha_emision of this SummaryDocument.  # noqa: E501

        Fecha en la que se emite el comprobante de Resumen Diario. Fecha expresada en milliseconds  # noqa: E501

        :return: The fecha_emision of this SummaryDocument.  # noqa: E501
        :rtype: int
        """
        return self._fecha_emision

    @fecha_emision.setter
    def fecha_emision(self, fecha_emision):
        """Sets the fecha_emision of this SummaryDocument.

        Fecha en la que se emite el comprobante de Resumen Diario. Fecha expresada en milliseconds  # noqa: E501

        :param fecha_emision: The fecha_emision of this SummaryDocument.  # noqa: E501
        :type: int
        """

        self._fecha_emision = fecha_emision

    @property
    def fecha_emision_de_comprobantes_asociados(self):
        """Gets the fecha_emision_de_comprobantes_asociados of this SummaryDocument.  # noqa: E501

        Fecha en la que todos los comprobantes, dentro del resumen, fueron emitidos. Fecha expresada en milliseconds  # noqa: E501

        :return: The fecha_emision_de_comprobantes_asociados of this SummaryDocument.  # noqa: E501
        :rtype: int
        """
        return self._fecha_emision_de_comprobantes_asociados

    @fecha_emision_de_comprobantes_asociados.setter
    def fecha_emision_de_comprobantes_asociados(self, fecha_emision_de_comprobantes_asociados):
        """Sets the fecha_emision_de_comprobantes_asociados of this SummaryDocument.

        Fecha en la que todos los comprobantes, dentro del resumen, fueron emitidos. Fecha expresada en milliseconds  # noqa: E501

        :param fecha_emision_de_comprobantes_asociados: The fecha_emision_de_comprobantes_asociados of this SummaryDocument.  # noqa: E501
        :type: int
        """
        if fecha_emision_de_comprobantes_asociados is None:
            raise ValueError("Invalid value for `fecha_emision_de_comprobantes_asociados`, must not be `None`")  # noqa: E501

        self._fecha_emision_de_comprobantes_asociados = fecha_emision_de_comprobantes_asociados

    @property
    def firmante(self):
        """Gets the firmante of this SummaryDocument.  # noqa: E501


        :return: The firmante of this SummaryDocument.  # noqa: E501
        :rtype: Firmante
        """
        return self._firmante

    @firmante.setter
    def firmante(self, firmante):
        """Sets the firmante of this SummaryDocument.


        :param firmante: The firmante of this SummaryDocument.  # noqa: E501
        :type: Firmante
        """

        self._firmante = firmante

    @property
    def numero(self):
        """Gets the numero of this SummaryDocument.  # noqa: E501

        Número de Resumen Diario emitido en el día  # noqa: E501

        :return: The numero of this SummaryDocument.  # noqa: E501
        :rtype: int
        """
        return self._numero

    @numero.setter
    def numero(self, numero):
        """Sets the numero of this SummaryDocument.

        Número de Resumen Diario emitido en el día  # noqa: E501

        :param numero: The numero of this SummaryDocument.  # noqa: E501
        :type: int
        """
        if numero is None:
            raise ValueError("Invalid value for `numero`, must not be `None`")  # noqa: E501

        self._numero = numero

    @property
    def proveedor(self):
        """Gets the proveedor of this SummaryDocument.  # noqa: E501


        :return: The proveedor of this SummaryDocument.  # noqa: E501
        :rtype: Object
        """
        return self._proveedor

    @proveedor.setter
    def proveedor(self, proveedor):
        """Sets the proveedor of this SummaryDocument.


        :param proveedor: The proveedor of this SummaryDocument.  # noqa: E501
        :type: Object
        """
        if proveedor is None:
            raise ValueError("Invalid value for `proveedor`, must not be `None`")  # noqa: E501

        self._proveedor = proveedor

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SummaryDocument, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SummaryDocument):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
